version: '3'

services:
  # FastAPI Serve
  fastapi:
    build: .
    ports:
      - "8000:8000"  

  # MySQL Serve
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./mysql-data:/var/lib/mysql  # MySQL data persistence

  # phpMyAdmin Serve
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"  
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql